title: Favour Izebhijie # your name (or website title) here
logo: "logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Favour zebhijie is a graduate of Computer Science, a Talented backend developer adept at contributing to highly collaborative work environment, finding solutions and determining customer satisfaction. 
  <br><br>
  Designed and developed web applications across multiple APIs, third-party integrations and databases. Passionate and hardworking with penchant for developing applications that factor in unique demands for accessibility, reachability and security 
  <br><br>
  <a href="https://www.linkedin.com/in/favour-izebhijie">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

